---
title: "neighborhood dataset"
author: "Ana Steiner"
date: "2024-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(zoo)
library(readxl)
library(stats)
library(readr) 
library(ggplot2)
library(sf)
library(tmap)
library(sp)
library(spdep)
library(MASS)
library(tidyverse)
library(stringr)
library(data.table)
```

```{r}
# Load the datasets

setwd("C:/Users/USUARIO/Documents/UCL/Dissertation/v3 longitudinal diaspora study/Data/neighborhood data")

religion_2001 <- read_csv("religion borough 2001.csv")
religion_2011 <- read_csv("religion lsoa 2011.csv")
religion_2021 <- read_csv("religion msoa 2021.csv")
greenery_df <- read_csv("greenery boroughs.csv")
crime_df <- read_csv("historic crime 2010-2021.csv")
ptal2015 <- read_csv("lsoa 2015 ptal.csv")
ptal2021 <- read_csv("grid 2021 ptal.csv")

# Spatial data
msoa <- st_read("C:/Users/USUARIO/Documents/UCL/Dissertation/v3 longitudinal diaspora study/Data/MSOA_2011_London_gen_MHW.shp")
lsoa <- st_read("C:/Users/USUARIO/Documents/UCL/Dissertation/v3 longitudinal diaspora study/Data/LSOA_2011_London_gen_MHW.shp")
borough <- st_read("C:/Users/USUARIO/Documents/UCL/Dissertation/v3 longitudinal diaspora study/Data/London_Borough_Excluding_MHW.shp")
```

```{r}
# Religion 2001
library(dplyr)

# Convert the columns representing religions to numeric, if necessary
religion_2001[ , 4:11] <- lapply(religion_2001[ , 4:11], as.numeric)

names(religion_2001)

#Eliminate columns
religion_2001 <- religion_2001[, -c(1, 3)]

# Define the function to find the majority religion
majority_religion <- function(row) {
  # Extract only the numeric values
  religion_counts <- c(
    Christian = row["Christian"],
    Buddhist = row["Buddhist"],
    Hindu = row["Hindu"],
    Jewish = row["Jewish"],
    Muslim = row["Muslim"],
    Sikh = row["Sikh"],
    `Other religions` = row["Other religions"],
    `No religion` = row["No religion"]
  )
  
  # Find the maximum value
  max_count <- max(religion_counts)
    # Find the names with the maximum value
  majority_religions <- names(religion_counts)[religion_counts == max_count]
  
  # Check for ties
  if (length(majority_religions) > 1) {
    return("No single majority")
  }
  
  return(majority_religions)
}


# Apply the function to each row
religion_2001$Majority_Religion <- apply(religion_2001, 1, majority_religion)

#Eliminate columns
religion_2001 <- religion_2001[, -c(2, 3, 4, 5, 6, 7, 8, 9)]

merged_2001_religion <- religion_2001 %>%
  left_join(msoa, by = c("Borough" = "LAD11NM"))

#Eliminate columns
merged_2001_religion <- merged_2001_religion[, -c(1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)]
```

```{r}
# Religion 2011

#Eliminate columns
religion_2011 <- religion_2011[, -c(2)]

# Rename columns for easier access
religion_2011 <- religion_2011 %>%
  rename(
    LSOA = `Lower Super Output Area`,
    Christian = `Religion;Christian;2011`,
    Buddhist = `Religion;Buddhist;2011`,
    Hindu = `Religion;Hindu;2011`,
    Jewish = `Religion;Jewish;2011`,
    Muslim = `Religion;Muslim;2011`,
    Sikh = `Religion;Sikh;2011`,
    Other_religion = `Religion;Other religion;2011`,
    No_religion = `Religion;No religion;2011`,
    Religion_not_stated = `Religion;Religion not stated;2011`
  )

# Convert relevant columns to numeric
religion_2011 <- religion_2011 %>%
  mutate(across(Christian:Religion_not_stated, as.numeric))

# Revised function to determine the majority religion
majority_religion <- function(Christian, Buddhist, Hindu, Jewish, Muslim, Sikh, Other_religion, No_religion, Religion_not_stated) {
  # Create a named vector of religion counts
  religion_counts <- c(
    Christian = Christian,
    Buddhist = Buddhist,
    Hindu = Hindu,
    Jewish = Jewish,
    Muslim = Muslim,
    Sikh = Sikh,
    Other_religion = Other_religion,
    No_religion = No_religion,
    Religion_not_stated = Religion_not_stated
  )
  
  # Remove NA values
  religion_counts <- na.omit(religion_counts)
  
  # Check if there are any valid counts left
  if (length(religion_counts) == 0) {
    return("No data available")
  }
  
  # Find the maximum count
  max_count <- max(religion_counts)
  
  # Identify which religions have the maximum count
  majority_religions <- names(religion_counts)[religion_counts == max_count]
  
  # Return the majority religion if there’s a clear winner
  if (length(majority_religions) == 1) {
    return(majority_religions)
  } else {
    return("No single majority")
  }
}

library(dplyr)

# Apply the function to each row
religion_2011 <- religion_2011 %>%
  rowwise() %>%
  mutate(Majority_Religion = majority_religion(
    Christian, Buddhist, Hindu, Jewish, Muslim, Sikh, Other_religion, No_religion, Religion_not_stated
  )) %>%
  ungroup()

#Eliminate columns
religion_2011 <- religion_2011[, -c(2, 3, 4, 5, 6, 7, 8, 9, 10)]

# Define a function to get the most frequent religion
most_frequent_religion <- function(religions) {
  # Count the occurrences of each religion
  counts <- table(religions)
  
  # Find the religion with the highest count
  max_count <- max(counts)
  most_frequent_religions <- names(counts)[counts == max_count]
  
  # Return the most frequent religion if there’s a clear winner
  if (length(most_frequent_religions) == 1) {
    return(most_frequent_religions)
  } else {
    return("No single majority")
  }
}

merged_2011_religion <- religion_2011 %>%
  left_join(lsoa, by = c("LSOA" = "LSOA11CD"))

# Aggregate by MSOA and determine the most frequent majority religion
aggregated_2011_religion <- merged_2011_religion %>%
  group_by(MSOA11CD) %>%  # Use MSOA11CD or MSOA11NM for grouping
  summarise(
    Most_Frequent_Religion = most_frequent_religion(Majority_Religion),
    .groups = 'drop'  # Drop the grouping structure
  )

# Join 2011 and 2001 religion
religion_joined <- merged_2001_religion %>%
  left_join(aggregated_2011_religion, by = "MSOA11CD")

# Rename columns using rename()
religion_joined  <- religion_joined  %>%
  rename(
    `2001` = `Majority_Religion`,
    `2011` = `Most_Frequent_Religion`,
  )
```

```{r}
# Religion 2021

# Rename the column 'Middle layer Super Output Areas Code' to 'msoa11cd'
religion_2021 <- religion_2021 %>%
  rename(msoa11cd = `Middle layer Super Output Areas Code`)

# Print column names to verify
print(names(religion_2021))

# Filter out 'Does not apply' and find the majority religion for each MSOA
majority_religion <- religion_2021 %>%
  filter(`Religion (detailed) (58 categories)` != "Does not apply") %>%
  group_by(msoa11cd) %>%
  slice(which.max(Observation)) %>%
  dplyr::select(msoa11cd, `Religion (detailed) (58 categories)`) %>%
  rename(religion = `Religion (detailed) (58 categories)`)

# join to shp
final_religion <- religion_joined %>%
  left_join(majority_religion, by = c("MSOA11CD" = "msoa11cd")) 

# Rename columns 
final_religion  <- final_religion  %>%
  rename(
    `2021` = `religion`,
  )

# Create a data frame with years 2011-2018
years <- data.frame(year = 2011:2018)

# Merge files
expanded_religion <- merge(majority_religion, years)
```

```{r}
# Interpolate religion

library(dplyr)
library(tidyr)
library(stringr)

# Convert data to long format
religion_long <- final_religion %>%
  pivot_longer(cols = starts_with("20"), names_to = "Year", values_to = "Religion") %>%
  mutate(Year = as.numeric(Year))

# Define the cleaning function
clean_religion <- function(religion) {
  parts <- str_split(religion, "[:.]")[[1]]
  parts <- str_trim(parts)
  unique_parts <- unique(parts)
  return(unique_parts[1])
}

# Clean the religion column
religion_cleaned <- religion_long %>%
  mutate(Religion = sapply(Religion, clean_religion))

library(zoo)

# Fill missing values
interpolated_data <- religion_cleaned %>%
  group_by(MSOA11CD) %>%
  arrange(Year) %>%
  mutate(Religion = na.locf(Religion, na.rm = FALSE)) %>%
  ungroup()

# Generate all combinations of MSOA11CD and odd years
years <- seq(2001, 2021, by = 2)
msoa_codes <- unique(religion_cleaned$MSOA11CD)
full_data <- expand.grid(MSOA11CD = msoa_codes, Year = years)

# Merge with the existing data
full_data <- full_data %>%
  left_join(religion_cleaned, by = c("MSOA11CD", "Year"))

# Interpolate missing religions using last observation carried forward (LOCF)
interpolated_religion <- full_data %>%
  group_by(MSOA11CD) %>%
  arrange(Year) %>%
  mutate(Religion = zoo::na.locf(Religion, na.rm = FALSE)) %>%
  ungroup()

```

```{r}
library(dplyr)

greenery_df_cleaned <- greenery_df %>%
  rename(area = lb_code) %>%  # Rename lb_code to area
  dplyr::select(area, percent_green) %>%  # Select the desired columns
  na.omit() %>%  # Remove rows with NA values
  mutate(percent_green = as.numeric(percent_green))

# Create a data frame with years 
years <- seq(2001, 2021, by = 2)

# Use merge() to perform a Cartesian join
expanded_grenery <- merge(greenery_df_cleaned, years)

# Change column name
names(expanded_grenery)[names(expanded_grenery) == "y"] <- "Year"

# Join to msoa chp
borough_greenery <- expanded_grenery %>%
  left_join(msoa, by = c("area" = "LAD11NM"))

# Calculate greenery of each msoa
borough_pop <- borough_greenery %>%
  group_by(LAD11CD) %>%
  summarize(total_borough_population = sum(USUALRES))

# Merge total borough population back to the original dataframe
borough_greenery <- merge(borough_greenery, borough_pop, by = "LAD11CD")

# Calculate the proportion of each MSOA in the borough
borough_greenery$population_proportion <- borough_greenery$USUALRES / borough_greenery$total_borough_population

# Assign greenery percentage to each MSOA
borough_greenery$MSOA_percent_green <- borough_greenery$population_proportion * borough_greenery$percent_green

# Select relevant columns for the result
msoa_green <- dplyr::select(borough_greenery, MSOA11CD, MSOA11NM, Year, MSOA_percent_green)
```

```{r}
# Crime data

# Rename 'Borough' column to 'Code'
crime_df <- crime_df %>% rename(code = Borough)

# Aggregate crime values by 'Code'
aggregated_crime <- crime_df %>%
  group_by(code) %>%
  summarise(across(starts_with("20"), sum, na.rm = TRUE))

# Sum values by year
aggregated_crime <- aggregated_crime %>%
  gather(key = "YearMonth", value = "Count", -code) %>%
  mutate(Year = substr(YearMonth, 1, 4)) %>%
  group_by(code, Year) %>%
  summarise(Yearly_Total = sum(Count)) %>%
  spread(key = Year, value = Yearly_Total)

# Filter to keep only years 2011-2018
years_to_keep <- as.character(seq(2011, 2018, by = 1))
odd_years <- years_to_keep[as.numeric(years_to_keep) %% 2 != 0]
final_crime <- dplyr::select(aggregated_crime, code, all_of(odd_years))

# Transform to long format
long_crime <- final_crime %>%
  pivot_longer(cols = `2011`:`2017`, names_to = "Year", values_to = "crime_counts")

# Define the range of odd years
full_years <- seq(2001, 2021, by = 2)

# Interpolation function
interpolate_crime_counts <- function(long_crime) {
  interpolated <- approx(
    x = long_crime$Year, 
    y = long_crime$crime_counts, 
    xout = full_years, 
    rule = 2  # use last observation for extrapolation
  )
  return(data.frame(Year = interpolated$x, crime_counts = interpolated$y))
}

# Apply interpolation for each 'code'
interpolated_crime <- long_crime %>%
  group_by(code) %>%
  do(interpolate_crime_counts(.)) %>%
  ungroup()

# Join to msoa chp
borough_crime <- interpolated_crime %>%
  left_join(msoa, by = c("code" = "LAD11CD"))

# Calculate greenery of each msoa
borough_pop <- borough_crime %>%
  group_by(code) %>%
  summarize(total_borough_population = sum(USUALRES))

# Merge total borough population back to the original dataframe
borough_crime <- merge(borough_crime, borough_pop, by = "code")

# Calculate the proportion of each MSOA in the borough
borough_crime$population_proportion <- borough_crime$USUALRES / borough_crime$total_borough_population

# Assign greenery percentage to each MSOA
borough_crime$MSOA_crime <- borough_crime$population_proportion * borough_crime$crime_counts

# Select relevant columns for the result
msoa_crime <- dplyr::select(borough_crime, MSOA11CD, MSOA11NM, Year, MSOA_crime)
```

```{r}
# PTAL

# Convert ptal2021 to an sf object
ptal_2021_sf <- ptal2021 %>%
  st_as_sf(coords = c("X", "Y"), crs = 27700)

lsoa <- st_transform(lsoa, crs = 27700)

# Perform spatial join with LSOA layer
ptal_lsoa_joined <- st_join(ptal_2021_sf, lsoa, join = st_within)

# Join ptals
final_ptal <- ptal_lsoa_joined %>%
  left_join(ptal2015, by = c("LSOA11CD" = "LSOA2011"))

clean_ptal <- dplyr::select(final_ptal, MSOA11CD, MSOA11NM, AI2021, AvPTAI2015)

clean_ptal <- clean_ptal %>%
  rename(`2021` = AI2021, `2015` = AvPTAI2015)

ptal_no_geometry <- st_drop_geometry(clean_ptal)

msoa_ptal <- ptal_no_geometry %>%
  group_by(MSOA11CD, MSOA11NM) %>%
  summarize(
    avg_2021 = mean(`2021`, na.rm = TRUE),
    avg_2015 = mean(`2015`, na.rm = TRUE),
  )

# Interpolate
# Transform to long format
ptal_long <- msoa_ptal %>%
  pivot_longer(cols = starts_with("avg"), names_to = "Year", values_to = "PTAL") %>%
  mutate(Year = as.integer(gsub("avg_", "", Year)),
         PTAL = round(PTAL))

# Assuming `long_crime` and `msoa` data frames are already defined
library(dplyr)

# Define the range of full years for interpolation
full_years <- seq(2001, 2021, by = 1)

# Interpolation function
interpolate_ptal <- function(ptal_long) {
  interpolated <- approx(
    x = ptal_long$Year, 
    y = ptal_long$PTAL, 
    xout = full_years, 
    rule = 2  # using last observation for extrapolation
  )
  return(data.frame(Year = interpolated$x, PTAL = interpolated$y))
}

# Filter out groups with fewer than 2 non-NA PTAL values
filtered_ptal_long <- ptal_long %>%
  group_by(MSOA11NM) %>%
  filter(sum(!is.na(PTAL)) >= 2) %>%
  ungroup()

# Apply interpolation for each 'MSOA11NM'
interpolated_ptal <- filtered_ptal_long %>%
  group_by(MSOA11NM) %>%
  do(interpolate_ptal(.)) %>%
  ungroup()
```

```{r}
# Join neighborhood dataset
neighborhood <- msoa_crime %>%
  full_join(msoa_green, by = c("MSOA11NM", "Year")) %>%
  full_join(interpolated_ptal, by = c("MSOA11NM", "Year"))

neighborhood_clean <- neighborhood %>%
  drop_na()

names(neighborhood_clean)

library(dplyr)

# Correcting the code to remove a column and rename another
neighborhood_clean <- neighborhood_clean %>%
  dplyr::select(-`MSOA11CD.y`) %>%
  dplyr::rename(MSOA11CD = `MSOA11CD.x`)

final_neighborhood <- neighborhood_clean %>%
  full_join(interpolated_religion, by = c("MSOA11CD", "Year"))

final_neighborhood_unique <- final_neighborhood %>%
  group_by(MSOA11CD, Year) %>%
  slice(1) %>%  # or use distinct() if all other columns are the same
  ungroup()

final_neighborhood_clean <- final_neighborhood_unique %>%
  drop_na()

library(dplyr)
# Filter out rows with empty geometries and select the first occurrence of each unique MSOA11NM
correct_geometry <- final_neighborhood_unique %>%
  dplyr::filter(!grepl("EMPTY", geometry)) %>%
  dplyr::group_by(MSOA11CD, MSOA11NM) %>%
  dplyr::slice(1) %>%  # Choose the first occurrence of non-empty geometry
  dplyr::ungroup() %>%
  dplyr::select(MSOA11CD, MSOA11NM, geometry)

# Join the correct geometry back to the main data frame
final_neighborhood_cleaner <- final_neighborhood_unique %>%
  dplyr::select(-geometry) %>%  # Remove the existing geometry column
  dplyr::left_join(correct_geometry, by = c("MSOA11CD", "MSOA11NM"))

neighborhood_cleanest <- na.omit(final_neighborhood_cleaner)
```

#### EDA

```{r}
# Changes in crime over time

# Calculate the change in crime rate from the first to the last year for each MSOA
crime_change <- neighborhood_cleanest %>%
  group_by(MSOA11CD) %>%
  summarize(change = last(MSOA_crime) - first(MSOA_crime))

# Classify the change
crime_change <- crime_change %>%
  mutate(change_category = case_when(
    change > 0 ~ "Increased",
    change < 0 ~ "Decreased",
    TRUE ~ "No Change"
  ))

# Merge with the spatial data
neighborhood_cleanest <- left_join(neighborhood_cleanest, crime_change, by = "MSOA11CD")

# Convert the 'geometry' column to an sf object, assuming WKT format
neighborhood_cleanester <- st_as_sf(neighborhood_cleanest, crs = 27700)

# Plot the map
tm_shape(neighborhood_cleanester) +
  tm_polygons("change_category", palette = c("red", "green", "grey"),
              title = "Crime Rate Change") +
  tm_layout(title = "Change in Crime Rates by MSOA")
```

```{r}
# Green space

# Use the most recent year for the green space percentage
green_space <- neighborhood_cleanester %>%
  filter(Year == max(Year))

# Plot the map
tm_shape(green_space) +
  tm_polygons("MSOA_percent_green", palette = "Greens", title = "Percent Green Space") +
  tm_layout(title = "Green Space Percentage by MSOA")
```

```{r}
# PTAL

# Use the most recent year for PTAL
ptal_data <- neighborhood_cleanester %>%
  filter(Year == max(Year))

# Plot the map
tm_shape(ptal_data) +
  tm_polygons("PTAL", palette = "Blues", title = "PTAL Level") +
  tm_layout(title = "Public Transport Accessibility Level by MSOA")

```

```{r}
# Changes in crime

# Filter data for specific years
selected_years <- neighborhood_cleanester %>% filter(Year %in% c(2001, 2005, 2011, 2015, 2021))

# Function to create map for a specific year
create_map <- function(data, year) {
  ggplot(data) +
    geom_sf(aes(fill = MSOA_crime)) +
    scale_fill_viridis_c() +
    theme_minimal() +
    ggtitle(paste("Crime Data for the Year", year)) +
    theme(legend.position = "bottom")
}

# Loop through each year and plot
for(year in c(2001, 2005, 2011, 2015, 2021)) {
  map_data <- selected_years %>% filter(Year == year)
  print(create_map(map_data, year))
}

```


```{r}
# Changes in religion

# Function to plot religion distribution for a specific year
plot_religion_map <- function(year) {
  religion_data <- neighborhood_cleanester %>%
    filter(Year == year)
  
  tm_shape(religion_data) +
    tm_polygons("Religion", palette = "Set3", title = "Religion") +
    tm_layout(title = paste("Religion Distribution in", year))
}

# Plot maps for the selected years
plot_religion_map(2001)
plot_religion_map(2005)
plot_religion_map(2011)
plot_religion_map(2015)
plot_religion_map(2021)

```

```{r}
# Correlation

library(dplyr)
library(corrplot)

# Select the variables of interest for the correlation matrix
df_selected <- neighborhood_cleanest %>%
  dplyr::select(MSOA_crime, MSOA_percent_green, PTAL, Religion)

# Convert 'Religion' to a numeric variable if it's categorical
df_selected$Religion <- as.numeric(as.factor(df_selected$Religion))

# Ensure all columns are numeric (if needed)
df_selected <- df_selected %>%
  mutate_if(is.character, as.numeric) %>%
  mutate_if(is.factor, as.numeric)

df_no_geometry <- df_selected %>%
  st_drop_geometry()

# Calculate the correlation matrix
correlation_matrix <- cor(df_no_geometry, use = "complete.obs")

# Print the correlation matrix
print(correlation_matrix)

library(corrplot)
# Visualize the correlation matrix
corrplot(correlation_matrix, method = "circle", type = "upper", order = "hclust",
         tl.col = "black", tl.srt = 45, addCoef.col = "black", number.cex = 0.7)
```

## Download CSV
```{r}
# Remove the geometry column from the data frame
neighborhood_no_geo <- as.data.frame(neighborhood_cleanester)
neighborhood_no_geo$geometry <- NULL

# Write the cleaned data frame to a CSV file
write.csv(neighborhood_no_geo, "neighborhood_data.csv", row.names = FALSE)
```


